### PR TITLE
Added support for PHP 8

### PR DESCRIPTION
**Pull request by omnilight**
### Short description of what this PR does:
- Adds support for PHP 8
- Increased version of PHPUnit to ^9.0

### Checklist
- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guide] and my PR follows them.
- [x ] I updated my branch with the master branch.
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] I have added necessary documentation about the functionality in the appropriate .md file
- [x ] I have added in line documentation to the code I modified

Relates to #93

### CODE REVIEW

**Comment by omnilight** [comment]
Had to remove `--prefer-lowest` from tests, due to the errors. Looks like we have to make it as a separate PR

**Comment by omnilight** [comment]
Working on fixing tests

**Comment by jcchavezs** [comment]
Awesome

**Comment by omnilight** [comment]
All tests have been passed. Could we merge this and release new beta?

**Comment by jcchavezs** [comment]
Thanks a lot for this!

**Pull request merged**
