### PR TITLE
Add return type Traversable to getIterator for php8.1 compatibility

### LINKED ISSUE #119: Add compatibility with php8.1
## Background
PHP 8.1 deprecates an ability to override internal methods with incompatible return types
https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.core.type-compatibility-internal

## Problem
Method `OpenTracing\NoopSpanContext::getIterator()` implements one from IteratorAggregate, which has a `\Traversable` as a return type, and so it will produce Deprecated notice.

## Proposal
Add `\Traversable` as a return type

### PR DESCRIPTION
**Pull request by viteksafronov**
### Short description of what this PR does:
- Adds return type to OpenTracing/NoopSpanContext::getIterator() method

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

Closes #119

### CODE REVIEW

**Comment by jcchavezs** [comment]
I think we should cut a release only supporting 8.0 and 8.1

**Comment by ecourtial** [comment]
> I think we should cut a release only supporting 8.0 and 8.1

That's tough. I humbly think we could gently wait for the PHP7 EOL in the end of the year before doing that.

**Comment by viteksafronov** [comment]
So can we merge it and release a new version?

**Comment by viteksafronov** [comment]
@jcchavezs sorry for explicit mention but we'd really appreciate it if these edits were released

**Comment by jcchavezs** [comment]
I am sorry I've been out. I will come back to this by tomorrow.

José Carlos Chávez


tir. 18. jan. 2022 kl. 17:21 skrev Victor Safronov ***@***.***

**Comment by viteksafronov** [comment]
@jcchavezs we are still waiting :( is there anyone else who can release these changes?

**Comment by jcchavezs** [comment]
In the end I added a patch release for this https://github.com/opentracing/opentracing-php/releases/tag/1.0.2

This did not introduce a breaking change.

**Pull request merged**
